const{test,page, expect}=require('@playwright/test');
const { table } = require('console');
test(' Place Order: Login before Checkout',async({page})=>{
    await page.goto('/');
    await expect(page.getByText('Category')).toBeVisible();
    await page.locator('#header > div > div > div > div.col-sm-8 > div > ul > li:nth-child(4) > a').click();
    await page.getByText(' Signup / Login').click();
    await expect(page.getByText('Login to your account')).toBeVisible();
    await page.locator('#form > div > div > div.col-sm-4.col-sm-offset-1 > div > form > input[type=email]:nth-child(2)').click();
    await page.locator('#form > div > div > div.col-sm-4.col-sm-offset-1 > div > form > input[type=email]:nth-child(2)').fill('allen23@gmail.com');
    await page.locator('#form > div > div > div.col-sm-4.col-sm-offset-1 > div > form > input[type=password]:nth-child(3)').click();
    await page.locator('#form > div > div > div.col-sm-4.col-sm-offset-1 > div > form > input[type=password]:nth-child(3)').fill('abc@123456');
    await page.getByRole('button',{name:'Login'}).click();
// await expect(page.getByText(' Logged in as ')).toBeVisible();
    await expect(page.getByText(' Logged in as ')).toBeVisible();
    await page.locator('#header > div > div > div > div.col-sm-8 > div > ul > li:nth-child(1) > a').click();
    await page.locator('body > section:nth-child(3) > div.container > div > div.col-sm-9.padding-right > div.features_items').scrollIntoViewIfNeeded();
    await page.locator('body > section:nth-child(3) > div.container > div > div.col-sm-9.padding-right > div.features_items > div:nth-child(3) > div > div.choose > ul > li > a').click();
    await page.locator('body > section > div > div > div.col-sm-9.padding-right > div.product-details > div.col-sm-7 > div > span > button').click();
    // await page.getByRole('button',{name:' Add to cart'}).click();
    await page.getByRole('button',{name:"Continue Shopping"}).click();
    await page.getByRole('listitem').filter({hasText:' Cart'}).click();
    await expect(page.locator('#do_action > div.container > div > div > a')).toBeVisible();
    await page.locator('#do_action > div.container > div > div > a').click();
    await expect(page.locator('#cart_items > div')).toBeVisible();
    await page.locator('#ordermsg > textarea').click();
    await page.locator('#ordermsg > textarea').fill('csabjdvia nds');
    await page.locator('#cart_items > div > div:nth-child(7) > a').click();
    await expect(page.locator('#cart_items > div > div.step-one > h2')).toBeVisible();
    await page.locator('#payment-form > div:nth-child(2) > div > input').click();                 
    await page.locator('#payment-form > div:nth-child(2) > div > input').fill('najasnkakn');
    await page.locator('#payment-form > div:nth-child(3) > div > input').click();
    await page.locator('#payment-form > div:nth-child(3) > div > input').fill('cdn');
    await page.locator('#payment-form > div:nth-child(4) > div.col-sm-4.form-group.cvc > input').click();
    await page.locator('#payment-form > div:nth-child(4) > div.col-sm-4.form-group.cvc > input').fill('311');
    await page.locator('#payment-form > div:nth-child(4) > div:nth-child(2) > input').click();
    await page.locator('#payment-form > div:nth-child(4) > div:nth-child(2) > input').fill('05');
    await page.locator('#payment-form > div:nth-child(4) > div:nth-child(3) > input').click();
    await page.locator('#payment-form > div:nth-child(4) > div:nth-child(3) > input').fill('2025');
    await page.getByRole('button',{name:'Pay and Confirm Order'}).click();
    await expect(page.getByText('Order Placed!')).toBeVisible();
    await page.locator('#header > div > div > div > div.col-sm-8 > div > ul > li:nth-child(5) > a').click();
    await expect(page.locator('#form > div > div > div > h2 > b')).toBeVisible();
    await page.locator('#form > div > div > div > div > a').click();

})